server:
    port: 8010

spring:
    datasource:
        url: jdbc:h2:mem:catalog;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
        platform: h2
        username: sa
        password:
        driver-class-name: org.h2.Driver
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
    h2:
        console:
        enabled: true
        path: /console
        settings:
            trace: false
            web-allow-others: false
    thymeleaf:
        mode: HTML
        cache: true